/*
 * mbs_ngap_ie_type.h
 *
 * 
 */

#ifndef _OpenAPI_mbs_ngap_ie_type_H_
#define _OpenAPI_mbs_ngap_ie_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_mbs_ngap_ie_type_NULL = 0, OpenAPI_mbs_ngap_ie_type_PDU_RES_SETUP_REQ, OpenAPI_mbs_ngap_ie_type_PDU_RES_REL_CMD, OpenAPI_mbs_ngap_ie_type_PDU_RES_MOD_REQ, OpenAPI_mbs_ngap_ie_type_HANDOVER_CMD, OpenAPI_mbs_ngap_ie_type_HANDOVER_REQUIRED, OpenAPI_mbs_ngap_ie_type_HANDOVER_PREP_FAIL, OpenAPI_mbs_ngap_ie_type_SRC_TO_TAR_CONTAINER, OpenAPI_mbs_ngap_ie_type_TAR_TO_SRC_CONTAINER, OpenAPI_mbs_ngap_ie_type_TAR_TO_SRC_FAIL_CONTAINER, OpenAPI_mbs_ngap_ie_type_RAN_STATUS_TRANS_CONTAINER, OpenAPI_mbs_ngap_ie_type_SON_CONFIG_TRANSFER, OpenAPI_mbs_ngap_ie_type_NRPPA_PDU, OpenAPI_mbs_ngap_ie_type_UE_RADIO_CAPABILITY, OpenAPI_mbs_ngap_ie_type_RIM_INFO_TRANSFER, OpenAPI_mbs_ngap_ie_type_SECONDARY_RAT_USAGE, OpenAPI_mbs_ngap_ie_type_PC5_QOS_PARA, OpenAPI_mbs_ngap_ie_type_EARLY_STATUS_TRANS_CONTAINER, OpenAPI_mbs_ngap_ie_type_UE_RADIO_CAPABILITY_FOR_PAGING, OpenAPI_mbs_ngap_ie_type_MBS_DIS_SETUP_REQ, OpenAPI_mbs_ngap_ie_type_MBS_DIS_SETUP_RSP, OpenAPI_mbs_ngap_ie_type_MBS_DIS_SETUP_FAIL, OpenAPI_mbs_ngap_ie_type_MBS_DIS_REL_REQ, OpenAPI_mbs_ngap_ie_type_MBS_SES_ACT_REQ, OpenAPI_mbs_ngap_ie_type_MBS_SES_DEACT_REQ, OpenAPI_mbs_ngap_ie_type_MBS_SES_UPD_REQ, OpenAPI_mbs_ngap_ie_type_MBS_SES_REQ, OpenAPI_mbs_ngap_ie_type_MBS_SES_RSP, OpenAPI_mbs_ngap_ie_type_MBS_SES_FAIL, OpenAPI_mbs_ngap_ie_type_MBS_SES_REL_RSP } OpenAPI_mbs_ngap_ie_type_e;

char* OpenAPI_mbs_ngap_ie_type_ToString(OpenAPI_mbs_ngap_ie_type_e mbs_ngap_ie_type);

OpenAPI_mbs_ngap_ie_type_e OpenAPI_mbs_ngap_ie_type_FromString(char* mbs_ngap_ie_type);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_mbs_ngap_ie_type_H_ */

